import type { Metadata } from "next";
import { Indie_Flower } from "next/font/google";
import "./globals.css";

const indieFlower = Indie_Flower({
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Useless Facts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${indieFlower.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
